name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your build steps here
      
      - name: Deploy to Development
        env:
          REMOTE_URL: ${{ secrets.DEV_REPO_URL }}
        run: |
          git push $REMOTE_URL HEAD:main
