# This is a basic workflow to help you get started with Actions

name: deploy to dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'


    - name: Connect to server via SSH
      uses: appleboy/ssh-action@master
      with:
        proxy_host: ${{ secrets.JUMPHOST }}
        proxy_port: ${{ secrets.JUMPPORT }}
        proxy_username: ${{ secrets.JUMPUSER }}
        proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}


        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.JUMPPORT }}

        script: |
          ls
      
    - name: Deploy to Development
      env:
          REMOTE_URL: ${{ secrets.DEV_REPO_URL }}
          run: |
          ls