name: Deploy to Development Environment

on:
  push:
    branches: [ development ]

env:
  ENVIRONMENT_NAME: Development
  DATABASE_URL: ${{ secrets.DEVELOPMENT_DATABASE_URL }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout code from repository
    - uses: actions/checkout@v2

    # build and deploy application
    - name: Build and Deploy
      run: |
        # replace with your build and deployment commands
